apiVersion: apps/v1
kind: Deployment
metadata:
  name: consumer
  namespace: signavio
spec:
  replicas: 3
  selector:
    matchLabels:
      app: consumer
  template:
    metadata:
      labels:
        app: consumer
    spec:
      containers:
      - name: consumer
        image: consumer:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 9000
