apiVersion: apps/v1
kind: Deployment
metadata:
  name: producer
  namespace: signavio
spec:
  replicas: 3
  selector:
    matchLabels:
      app: producer
  template:
    metadata:
      labels:
        app: producer
    spec:
      containers:
      - name: producer
        image: producer:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 8000
